---
title: "Liver bud development"
author: "Yutong Wang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this vignette, we analyze the liver bud dataset from [Camp et al 2017](https://www.nature.com/articles/nature22796)

```{r}
library(corgi)
```

```{r}
con <- gzcon(url("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE81nnn/GSE81252/suppl/GSE81252_data.cast.log2.liverbud.csv.gz"))
txt <- readLines(con)

liverbud <- read.csv(file = textConnection(txt))

metadata <- liverbud[,1:3]
counts <- t(as.matrix(liverbud[,4:ncol(liverbud)]))

colnames(counts) <- metadata$cell_id

rownames(metadata) <- metadata$cell_id

metadata$LB_status <- 
  unlist(lapply(X = metadata$assignment_LB,
                FUN = function(x) ifelse(test = grepl("LB",x),yes = "LB",no = "IN")
                ))

metadata$lineage <- 
  factor(unlist(
    lapply(X = metadata$assignment_LB,
           FUN = function(x) strsplit(as.character(x),split = "-",fixed = T)[[1]][1])
    ))

table(metadata$LB_status,metadata$lineage)
```

```{r}
library(scran)
camp <- SingleCellExperiment(assays = list(logcounts = counts),colData = metadata)

IN <- camp[,camp$LB_status=="IN"]
LB <- camp[,camp$LB_status=="LB"]

out <- scran::multiBatchNorm(IN,LB,assay.type = "logcounts")
IN <- out[[1]]
LB <- out[[2]]

combined <- cbind(logcounts(IN),logcounts(LB))

pc <- prcomp(t(combined),rank. = 2)$x
```


```{r}
library(ggplot2)
library(forcats)
lineage <- fct_c(IN$lineage,LB$lineage)
batch <- c(rep("Input",ncol(IN)),rep("Liver bud",ncol(LB)))
qplot(pc[,1],pc[,2],color = lineage,shape = batch)
```

```{r, eval = F}
res_list_liver_bud <- run_corgi(logcounts(IN),logcounts(LB),n_phases = 3,time_per_phase = 10*60)
```

```{r}
data("res_list_liver_bud")
corgi_gene_set <- select_top_corgi_genes(res_list_liver_bud,300)

pc <- prcomp(t(combined[corgi_gene_set,]),rank. = 2)$x
qplot(pc[,1],pc[,2],color = lineage,shape = batch)
```
